---

- hosts: localhost
  gather_facts: false
  connection: local
  become: true

  vars_prompt:
          - name: "vm_hostname"
            prompt: "Enter vm hostname"
            private: no

          - name: "vm_user"
            prompt: "Enter vm username"
            private: no

          - name: "vm_pass"
            prompt: "Enter vm password"
            private: yes


  tasks:
          - vsphere_guest:
                  vcenter_hostname: "{{ vm_hostname }}"
                  username: "{{ vm_user }}"
                  password: "{{ vm_pass }}"
                  guest: "testingvm"
                  state: powered_on
                  validate_certs: false
                  vm_extra_config:
                          vcpu.hotadd: yes
                          mem.hotadd: yes
                          notes: "Created by Ansible"
                  vm_disk:
                          disk1:
                                  size_gb: "20"
                                  type: thin
                                  datastore: "QNAP-Datastore"
                  vm_nic:
                          nic1:
                                  type: vmxnet3
                                  network: "vlan78"
                                  network_type: standard
                  vm_hardware:
                          memory_mb: 1024
                          num_cpus: 1
                          osid: centos64Guest
                          scsi: paravirtual
                          vm_cdrom:
                                  type: "iso"
                                  iso_path: "local_datastore1/iso/CentOS-7-x86_64-DVD.iso"
                  esxi:
                          datacenter: ha-datacenter
                          hostname: "esxi-1"
...

